services:
  - type: web
    name: peer-evaluation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn peer_eval.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: DATABASE_URL
        fromDatabase:
          name: peer-eval-db
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        value: peerevaluation
