services:
  - type: web
    name: peer-evaluation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn peer_eval.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "django-insecure-nuk-a@%t%nugdy^8n*!=uoo)e-vo30q701s+l52v-42g4l(ig="
      - key: DATABASE_URL
        fromDatabase:
          name: peer-eval-db
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        value: peerevaluation
